{{- if and (not .Values.auth.existingSecret) .Values.auth.totpMasterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vesma.fullname" . }}
  labels:
    {{- include "vesma.labels" . | nindent 4 }}
type: Opaque
stringData:
  totp-master-key: {{ .Values.auth.totpMasterKey | quote }}
{{- end }}
