"""ADR-0038 M1: the shared BFS walker (``walker.py``) — direction and
edge-kind filters, fail-closed limits, the project id prefix guard, and
the trace_path byte-pin.

Contract pins:

* one walker: ``trace_path`` rides :func:`walker.walk_bfs` with the
  ``out`` default — its answers are byte-identical to the
  pre-extraction tool (existing corpus unchanged + a JSON pin of a live
  request, ``tests/data/codegraph_trace_pin/trace_out_default.json``);
* ``direction`` (``in``/``both``) and ``edge_kinds`` are the NEW M1
  surface — every leg is a point query (no recursive CTE), the BOTH
  expansion walks the incoming leg first (deterministic), and the kind
  filter rides per-kind capped queries (OR-semantics, no overlap);
* the fail-closed limits (ADR-0038 condition 3): a depth outside
  ``[1, 2]``, an unknown direction, a bare-string kind list, a set (an
  unordered container), a bool depth — every breach is a REFUSAL
  before any store access, never a silently different walk;
* the project boundary at the followed endpoint (condition 5): an id
  whose project prefix does not match is NOT followed — the walk sets
  ``truncated`` (the default-direction answers stay byte-identical
  because real indexes never produce cross-project edges);
* caps: fanout 32 (the ``+1`` probe slices + flags), total work 512 —
  the same numbers the ``trace`` schema card reports;
* PG1 row shape: node rows carry shapes only — no ``signature``, no
  literal content (condition 4).

Pin regeneration discipline: the committed JSON was captured by
indexing the pin recipe tree (a copy of the tool suite's mini_repo
content minus its test/longlines/longname/secret extras — exactly the
``_pin_repo`` builder below, deterministic), stamping
``last_indexed:8:pinproj = 2026-10-06T00:00:00+00:00`` in the sidecar
meta and issuing ``trace_path('pinproj', 'Derived', depth=2)``
(defaults: out, unfiltered, 3200 tokens). The pin is regenerated by the
same recipe, never hand-edited — a byte diff is a finding either way.
"""

from __future__ import annotations

import json
from collections.abc import Iterator
from pathlib import Path

import pytest

pytest.importorskip("tree_sitter_python", reason="code-graph extra not installed")

from tests.test_codegraph_tools import AGENT
from vesmaro.codegraph.service import CodeGraphService
from vesmaro.codegraph.walker import WalkLimitError, node_row, validate_walk_limits, walk_bfs
from vesmaro.config import CodeGraphConfig

#: The committed byte-pin: one live default (out, depth 2, unfiltered)
#: trace_path response, captured on the builder fixture at M1 ship
#: time.
PIN_DIR = Path(__file__).parent / "data" / "codegraph_trace_pin"
PIN_FILE = PIN_DIR / "trace_out_default.json"
PIN_TIMESTAMP = "2026-10-06T00:00:00+00:00"


# ── shared fixture tree (the pin recipe, minus the poison extras) ────────────


def _pin_repo(tmp_path: Path, name: str = "pinrepo") -> Path:
    """The pin recipe tree: helper (class + fn), app (imports, subclass,
    call). Deterministic content — the same bytes the committed pin was
    captured on."""
    root = tmp_path / name
    pkg = root / "pkg"
    pkg.mkdir(parents=True)
    (root / "pyproject.toml").write_text("[project]\nname = 'pinrepo'\n", encoding="utf-8")
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "helper.py").write_text(
        "class Base:\n"
        "    def greet(self):\n"
        "        return 'hi'\n"
        "\n"
        "def make_base():\n"
        "    return Base()\n",
        encoding="utf-8",
    )
    (root / "app.py").write_text(
        "from pkg.helper import Base, make_base\n"
        "\n"
        "class Derived(Base):\n"
        "    pass\n"
        "\n"
        "def run():\n"
        "    b = make_base()\n"
        "    b.greet()\n"
        "    return b\n",
        encoding="utf-8",
    )
    return root


# ── unit: fail-closed limits ─────────────────────────────────────────────────


class TestWalkLimitValidation:
    def test_defaults_pass_through(self) -> None:
        assert validate_walk_limits(2, "out", None) == (2, "out", None)
        assert validate_walk_limits(1, "both", []) == (1, "both", None)

    def test_depth_clamp_is_fail_closed(self) -> None:
        for bad in (0, 3, -1, True, "2", 2.0):
            with pytest.raises(WalkLimitError, match="depth must be an integer"):
                validate_walk_limits(bad, "out", None)

    def test_direction_vocabulary(self) -> None:
        for bad in ("OUT", "in/", "bothways", "", None, 3):
            with pytest.raises(WalkLimitError, match="direction must be one of"):
                validate_walk_limits(1, bad, None)
        for ok in ("in", "out", "both"):
            assert validate_walk_limits(1, ok, None)[1] == ok

    def test_kind_filter_vocabulary_and_shape(self) -> None:
        assert validate_walk_limits(1, "out", ["CALLS", "USES"]) == (1, "out", ("CALLS", "USES"))
        # duplicates collapse preserving order; empty = no filter
        assert validate_walk_limits(1, "out", ["USES", "USES"]) == (1, "out", ("USES",))
        # a bare string is a shape bug, not a one-kind walk
        with pytest.raises(WalkLimitError, match="must be a list or tuple"):
            validate_walk_limits(1, "out", "CALLS")
        # a set walks nondeterministically — refused outright
        with pytest.raises(WalkLimitError, match="must be a list or tuple"):
            validate_walk_limits(1, "out", {"CALLS"})  # type: ignore[arg-type]
        with pytest.raises(WalkLimitError, match="edge kind must be one of"):
            validate_walk_limits(1, "out", ["CALLS", "MAGICAL_KIND"])


# ── byte pin + directions + kinds through the REAL service ───────────────────


@pytest.fixture
def indexed_pin(tmp_path: Path) -> Iterator[CodeGraphService]:
    """The indexed pin recipe tree as ``pinproj`` (the exact live
    request the committed JSON captures). The freshness meta is
    RE-STAMPED to the capture era — the only wall-clock field of the
    response becomes reproducible, so the pin asserts the FULL payload
    byte-for-byte."""
    from tests.test_codegraph_tools import FakeMainStore, FakeProject

    repo = _pin_repo(tmp_path)
    main = FakeMainStore(FakeProject(id="p-pin", name="pinproj", paths=[str(repo)]))
    svc = CodeGraphService(main, tmp_path / "data", CodeGraphConfig(enabled=True))
    result = svc.index_project("pinproj", agent=AGENT, session="sess-pin")
    assert result["status"] == "ok", result
    svc.store.set_meta(f"last_indexed:{len('pinproj')}:pinproj", PIN_TIMESTAMP)
    try:
        yield svc
    finally:
        svc.close()


class TestTracePathBytePin:
    def test_default_out_depth2_pins_byte_for_byte(self, indexed_pin: CodeGraphService) -> None:
        """The live request (out, depth 2, unfiltered) over the pin
        recipe tree equals the committed JSON EXACTLY — key order
        included (a dict-equality pin would miss a key-order drift);
        the re-stamped ``last_indexed_at`` makes the wall-clock field
        reproducible, so NOTHING is popped."""
        payload = indexed_pin.trace_path("pinproj", "Derived", agent=AGENT, session="sess-pin")
        committed = json.loads(PIN_FILE.read_text(encoding="utf-8"))
        assert json.loads(json.dumps(payload, ensure_ascii=False)) == committed
        assert committed["last_indexed_at"] == PIN_TIMESTAMP  # stamp format contract

    def test_pin_shape_has_nine_contract_keys(self, indexed_pin: CodeGraphService) -> None:
        trace = indexed_pin.trace_path("pinproj", "Derived", agent=AGENT)
        assert set(trace) == {
            "project",
            "start",
            "depth",
            "nodes",
            "edges",
            "truncated",
            "cursor",
            "has_more",
            "last_indexed_at",
        }
        assert trace["start"] == "Derived"
        assert trace["depth"] == 2
        assert trace["last_indexed_at"] is not None


class TestWalkerDirection:
    def test_in_direction_walks_the_reverse_edge(self, indexed_pin: CodeGraphService) -> None:
        """«Who calls/inherits X»: the incoming walk from ``Base``
        reaches ``Derived`` (trace_path could NEVER answer this before
        M1) and the edge row keeps the contract orientation
        (``from``=Derived, ``to``=Base — the EDGE's own direction,
        never flipped for display)."""
        trace = indexed_pin.trace_path("pinproj", "Base", agent=AGENT, depth=1, direction="in")
        assert trace["start"] == "Base"
        reached = {n["qname"] for n in trace["nodes"]}
        assert "Derived" in reached
        edge = next(e for e in trace["edges"] if e["kind"] == "INHERITS")
        assert edge["from"].endswith("#app.py#Derived#3")
        assert edge["to"].endswith("#pkg/helper.py#Base#1")
        assert trace["truncated"] is False

    def test_both_direction_visits_union(self, indexed_pin: CodeGraphService) -> None:
        both = indexed_pin.trace_path("pinproj", "Base", agent=AGENT, depth=1, direction="both")
        started = {n["qname"] for n in both["nodes"]}
        assert {"Derived"} <= started  # the incoming leg fired

    def test_direction_in_never_leaks_outgoing_legs(self, indexed_pin: CodeGraphService) -> None:
        """The negative pin of direction=in: ``run`` CALLS make_base —
        the in-walk from ``make_base`` reaches its incoming CALLER
        chain only; ``pkg.helper.Base`` (called BY make_base) must
        NEVER enter the in-walk closure (a broken direction logic would
        drag it in)."""
        trace = indexed_pin.trace_path("pinproj", "make_base", agent=AGENT, depth=2, direction="in")
        reached = {n["qname"] for n in trace["nodes"]}
        assert "make_base" in reached
        # out-leg leak check: make_base CALLS Base — a broken direction
        # logic would drag Base into the closure.
        assert not any(q.startswith("Base") for q in reached)
        assert not any("greet" in q for q in reached)
        # and the incoming caller IS reachable (call chain run → make_base)
        assert "run" in reached


class TestWalkerKindFilter:
    def test_kind_filter_narrows_the_walk(self, indexed_pin: CodeGraphService) -> None:
        trace = indexed_pin.trace_path(
            "pinproj", "Derived", agent=AGENT, depth=2, edge_kinds=["INHERITS"]
        )
        kinds = {e["kind"] for e in trace["edges"]}
        assert kinds == {"INHERITS"}
        assert len(trace["edges"]) >= 1

    def test_kind_filter_or_semantics(self, indexed_pin: CodeGraphService) -> None:
        trace = indexed_pin.trace_path(
            "pinproj", "Derived", agent=AGENT, depth=2, edge_kinds=["INHERITS", "CALLS"]
        )
        kinds = {e["kind"] for e in trace["edges"]}
        assert kinds <= {"INHERITS", "CALLS"}
        assert kinds  # at least one fired

    def test_kind_filter_unknown_kind_refused(self, indexed_pin: CodeGraphService) -> None:
        with pytest.raises(Exception, match="edge kind must be one of"):
            indexed_pin.trace_path("pinproj", "Base", agent=AGENT, edge_kinds=["NOT_A_KIND"])

    def test_unknown_direction_refused_at_tool_level(self, indexed_pin: CodeGraphService) -> None:
        with pytest.raises(Exception, match="direction must be one of"):
            indexed_pin.trace_path("pinproj", "Base", agent=AGENT, direction="sideways")

    def test_bad_depth_refused_at_tool_level(self, indexed_pin: CodeGraphService) -> None:
        with pytest.raises(Exception, match="depth must be an integer"):
            indexed_pin.trace_path("pinproj", "Base", agent=AGENT, depth=3)


# ── caps + project boundary (walker unit, fake store) ────────────────────────


class _TinyEdge:
    def __init__(self, from_id: str, to_id: str, kind: str = "CALLS") -> None:
        self.from_id = from_id
        self.to_id = to_id
        self.kind = kind
        self.weight = 1.0
        self.provenance = "tree-sitter"


class _FakeWalkNode:
    def __init__(self, nid: str, qname: str) -> None:
        self.id = nid
        self.qname = qname
        self.kind = "Function"
        self.path = "f.py"
        self.start_line = 1
        self.end_line = 1


class _FakeWalkStore:
    """A minimal edge source the walker unit tests ride: preloaded
    adjacency (both directions), a GLOBAL get_node (the real store's
    «resolves ids globally» shape — exactly what the prefix guard is
    defending against)."""

    def __init__(self) -> None:
        self.edges: list[_TinyEdge] = []
        self.nodes: dict[str, _FakeWalkNode] = {}

    def add(self, p: str, name: str) -> str:
        nid = f"{len(p)}:{p}#f.py#{name}#1"
        self.nodes[nid] = _FakeWalkNode(nid, f"{p}.{name}")
        return nid

    def add_cross(self, p: str, name: str) -> str:
        """An id that belongs to the SIBLING project (prefix mismatch)."""
        sib = p + "2"
        nid = f"{len(sib)}:{sib}#f.py#{name}#1"
        self.nodes[nid] = _FakeWalkNode(nid, f"{sib}.{name}")
        return nid

    def link(self, a: str, b: str, kind: str = "CALLS") -> None:
        self.edges.append(_TinyEdge(a, b, kind))

    def get_edges(
        self,
        project: str,
        *,
        from_id: str | None = None,
        to_id: str | None = None,
        kind: str | None = None,
        limit: int = 200,
    ) -> list[_TinyEdge]:
        out: list[_TinyEdge] = []
        for e in self.edges:
            if from_id is not None and e.from_id != from_id:
                continue
            if to_id is not None and e.to_id != to_id:
                continue
            if kind is not None and e.kind != kind:
                continue
            out.append(e)
            if len(out) >= limit:
                break
        return out

    def get_node(self, node_id: str) -> _FakeWalkNode | None:
        return self.nodes.get(node_id)


def _sort_key(r: dict[str, object]) -> tuple[object, ...]:
    return (r["depth"], str(r["qname"]))  # type: ignore[return-value]


class TestWalkerCapsAndBoundary:
    def test_fanout_cap_slices_and_flags(self) -> None:
        store = _FakeWalkStore()
        p = "fanproj"
        hub = store.add(p, "hub")
        for i in range(40):  # > 32: the cap must bind
            store.link(hub, store.add(p, f"m{i:02d}"))
        walk = walk_bfs(store, p, hub, store.nodes[hub], depth=1, direction="out")
        assert len([n for n in walk["rows"] if n["depth"] == 1]) == 32
        assert walk["truncated"] is True

    def test_fanout_cap_under_cap_no_flag(self) -> None:
        store = _FakeWalkStore()
        p = "fanproj"
        hub = store.add(p, "hub")
        for i in range(10):
            store.link(hub, store.add(p, f"m{i:02d}"))
        walk = walk_bfs(store, p, hub, store.nodes[hub], depth=1, direction="out")
        assert walk["truncated"] is False

    def test_total_work_cap_bounds_visited(self) -> None:
        store = _FakeWalkStore()
        p = "workproj"
        a = store.add(p, "a")
        b = store.add(p, "b")
        store.link(a, b)
        for i in range(200):
            store.link(a, store.add(p, f"x{i:03d}"), kind="USES")
        walk = walk_bfs(store, p, a, store.nodes[a], depth=2, direction="out")
        rows = walk["rows"]
        assert len(rows) <= 512
        assert walk["truncated"] is True
        # deterministic: the first-level leg (a→b) survives the cap
        assert any(r["qname"] == f"{p}.b" for r in rows)
        assert sorted(rows, key=_sort_key) == rows  # the pinned (depth, qname) sort

    def test_cross_project_endpoint_never_followed(self) -> None:
        """ADR-0038 condition 5 at the WALKER level: the edge to the
        sibling project's id is skipped WHOLE (no row, no node) and the
        walk reports truncated."""
        store = _FakeWalkStore()
        p = "boundproj"
        a = store.add(p, "a")
        foreign = store.add_cross(p, "secret_node")
        store.link(a, foreign, kind="IMPORTS")
        walk = walk_bfs(store, p, a, store.nodes[a], depth=1, direction="out")
        assert walk["truncated"] is True
        assert walk["edges"] == []  # the foreign edge NEVER reported
        assert len(walk["rows"]) == 1  # only the start row
        assert all("2:boundproj" not in r["id"] for r in walk["rows"])  # no leak

    def test_same_project_prefix_length_guard(self) -> None:
        from vesmaro.codegraph.walker import same_project_prefix

        assert same_project_prefix("8:miniproj#a.py#x#1", "miniproj")
        assert not same_project_prefix("9:miniproj2#a.py#x#1", "miniproj")
        assert not same_project_prefix("7:minipro#a.py#x#1", "miniproj")

    def test_in_direction_follows_the_from_endpoint(self) -> None:
        store = _FakeWalkStore()
        p = "inproj"
        a = store.add(p, "a")
        b = store.add(p, "b")
        store.link(b, a)  # b -> a: an INCOMING edge at a
        walk = walk_bfs(store, p, a, store.nodes[a], depth=1, direction="in")
        reached = {r["id"] for r in walk["rows"]}
        assert b in reached
        assert walk["edges"][0]["from"] == b and walk["edges"][0]["to"] == a

    def test_node_row_pg1_shape_no_signature(self) -> None:
        class _N:
            id, qname, kind, path = "x:node", "n", "Function", "a.py"
            start_line, end_line = 1, 2
            signature = "def n(): ..."  # NEVER issued by the row builder

        row = node_row(_N(), 1)
        assert set(row) == {"id", "qname", "kind", "path", "start_line", "end_line", "depth"}
        assert "signature" not in row


class TestSchemaCardCaps:
    def test_trace_caps_reported_by_schema(self, indexed_pin: CodeGraphService) -> None:
        card = indexed_pin.get_graph_schema("pinproj", agent=AGENT)
        assert card["trace"] == {"max_depth": 2, "fanout_cap": 32, "total_work_cap": 512}
