"""``vesma completion`` CLI subcommand — custom shell completion auto-install.

Installs Vesma's OWN completion scripts (backed by the ``vesma __complete``
engine, :mod:`vesmaro.cli.complete_cmd`) instead of typer's generated ones,
which carry no candidate descriptions in any shell. The custom scripts
surface commands/subcommands/options WITH their descriptions in zsh and
fish; bash's readline cannot render descriptions, so it completes values
only (honestly documented in ``--show-instructions`` and the user docs).

Prog binding
------------

The scripts are bound to the PRIMARY program name — the ``sys.argv[0]``
basename at install time when it is one of Vesma's real binary names,
defaulting to ``vesma`` — plus the legacy alias names that exist as real
binaries (``vesmaro`` always, ``mnemos`` when found on PATH). Each
registered name gets the same completion function, so Tab works for every
way the user actually invokes the CLI. This fixes the historical bug where
the installer registered completion for ``vesmaro`` while the binary users
invoke is ``vesma`` (dead Tab completion), compounded by stale pre-rebrand
``source ~/.mnemos/completion/vesmaro.bash`` rc lines making the installer
report "already installed".

File layout::

    ~/.mnemos/
      ├── data/
      ├── vault/
      ├── logs/
      ├── cache/
      └── completion/           ← generated by this command
          ├── vesma.bash
          ├── vesma.zsh
          └── vesma.fish
    ~/.config/fish/completions/<name>.fish   ← fish auto-sourced (per name)

Subcommand tree::

    vesma completion                     — auto-detect shell + auto-install
    vesma completion bash|zsh|fish        — explicit shell + auto-install
    vesma completion --show-instructions — print manual steps, no file changes

Installer semantics: every run REWRITES the script files (stay in sync with
the installed vesma version) and ensures EXACTLY ONE canonical guarded
source line per shell in the rc file. All legacy forms are migrated away:
old ``eval "$(… --show-completion …)"`` lines, ``# Added by`` marker
comments, ``if [ -f … ]; then source …; fi`` blocks and ``[ -f … ] &&
source …`` one-liners referencing ANY old script name (mnemos.bash,
vesmaro.bash, vesma.zsh, ...). ``_is_installed`` matches ONLY the exact
canonical line — a stale legacy line is never mistaken for an install.
"""

from __future__ import annotations

import contextlib
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

console = Console()

completion_app = typer.Typer(
    name="completion",
    help="Install shell completion for vesma (auto-detect + auto-install).",
    no_args_is_help=False,
)

# Shells we support for auto-install.
_SUPPORTED_SHELLS = ("bash", "zsh", "fish")

# Real binary names Vesma has shipped under. The primary name is derived
# from sys.argv[0] only when it is one of these (a pytest/uv-run argv must
# not rename the installed scripts); otherwise the brand default wins.
_KNOWN_PROG_NAMES = ("vesma", "vesmaro", "mnemos")
_DEFAULT_PROG_NAME = "vesma"


def _primary_prog_name() -> str:
    """Primary program name: ``sys.argv[0]`` basename when it is a known
    Vesma binary, else the brand default ``vesma``."""
    argv0 = Path(sys.argv[0] if sys.argv else "").name
    if argv0 in _KNOWN_PROG_NAMES:
        return argv0
    return _DEFAULT_PROG_NAME


def _prog_names() -> list[str]:
    """All program names the completion must be bound to.

    Primary first, then legacy aliases: ``vesmaro`` always (the historical
    binary name), ``mnemos`` only when it exists as a real binary on PATH.
    """
    primary = _primary_prog_name()
    names = [primary]
    if "vesmaro" not in names:
        names.append("vesmaro")
    if "mnemos" not in names and shutil.which("mnemos"):
        names.append("mnemos")
    return names


# ── Paths ─────────────────────────────────────────────────────────────────────


def _completion_dir() -> Path:
    """Directory holding the generated scripts: ``~/.mnemos/completion``."""
    return Path.home() / ".mnemos" / "completion"


def _completion_file_path(shell: str) -> Path:
    """Path of the stored completion script for the given shell."""
    return _completion_dir() / f"{_primary_prog_name()}.{shell}"


def _fish_completions_file(prog: str) -> Path:
    """fish's auto-sourced completions file for one program name."""
    return Path.home() / ".config" / "fish" / "completions" / f"{prog}.fish"


def _rc_path(shell: str) -> Path:
    """Rc file receiving the completion for the given shell.

    For bash/zsh this is the rc file that receives the canonical ``source``
    line. For fish there is no rc line (fish auto-sources its completions
    directory) — the path returned is the PRIMARY program's completions
    file, which is what "installed" means for fish.
    """
    home = Path.home()
    if shell == "bash":
        return home / ".bashrc"
    if shell == "zsh":
        return home / ".zshrc"
    if shell == "fish":
        return _fish_completions_file(_primary_prog_name())
    raise ValueError(f"Unsupported shell: {shell}")


def _canonical_source_line(shell: str) -> str:
    """The ONE guarded source line the installer guarantees in the rc file.

    ``_is_installed`` compares rc lines against this exact string — never a
    substring match — so stale lines merely MENTIONING the completion dir
    (pre-rebrand ``vesmaro.bash``, ``mnemos.bash`` one-liners/if-blocks)
    can never be mistaken for an installed completion.
    """
    path = _completion_file_path(shell)
    tilde_path = f"~/{path.relative_to(Path.home())}"
    return f"[ -f {tilde_path} ] && source {tilde_path}"


# ── Script generation (per shell, backed by `vesma __complete`) ──────────────


def _bash_script(prog_names: list[str]) -> str:
    """bash completion script: feed COMP_WORDS/COMP_CWORD to the engine.

    bash's readline cannot render candidate descriptions — only the value
    column (before the first TAB) is completed. Commands, subcommands,
    options and option values complete at ALL levels because the engine
    does the walking; the glue is stateless.
    """
    bound = " ".join(prog_names)
    return f"""\
# vesma bash completion — custom engine backed by `{prog_names[0]} __complete`.
# Installed by `{prog_names[0]} completion bash`; rewritten on every run.
# NOTE: bash's readline cannot show candidate descriptions; values only.

_{prog_names[0]}() {{
    local line value
    while IFS= read -r line; do
        value="${{line%%$'\\t'*}}"
        [ -n "$value" ] && COMPREPLY+=("$value")
    done < <({prog_names[0]} __complete "${{COMP_WORDS[@]:1}}" "$((COMP_CWORD - 1))" 2>/dev/null)
    return 0
}}
# Bound to every registered program name (primary + legacy aliases).
complete -F _{prog_names[0]} {bound}
"""


def _zsh_script(prog_names: list[str]) -> str:
    """zsh completion script: value/description pairs via _describe.

    The engine emits ``value<TAB>description`` lines; the glue splits on the
    TAB so zsh SHOWS the descriptions in its completion menu. Source this
    file AFTER ``compinit`` in ``~/.zshrc`` (the guarded compdef below is a
    no-op otherwise).
    """
    bound = " ".join(prog_names)
    compdefs = " ".join(prog_names)
    raw_call = (
        f'raw="$({prog_names[0]} __complete "${{(@)words[2,-1]}}" '
        f'"$((CURRENT - 2))" 2>/dev/null)" || return 0'
    )
    return f"""\
#compdef {bound}
# vesma zsh completion — custom engine backed by `{prog_names[0]} __complete`.
# Installed by `{prog_names[0]} completion zsh`; rewritten on every run.
# Source this file AFTER compinit in ~/.zshrc so compdef can bind.

_{prog_names[0]}() {{
    local -a completions
    local raw line word desc
    {raw_call}
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        word="${{line%%$'\\t'*}}"
        desc="${{line#*$'\\t'}}"
        [[ "$desc" == "$line" ]] && desc=""
        completions+=("${{word}}:${{desc}}")
    done <<< "$raw"
    (( ${{#completions[@]}} )) || return 0
    _describe -t {prog_names[0]}-completions '{prog_names[0]} completion' completions
}}
# Bind every registered program name (primary + legacy aliases).
if (( $+functions[compdef] )); then
  compdef _{prog_names[0]} {compdefs}
fi
"""


def _fish_script(prog_names: list[str]) -> str:
    """fish completion script: one ``complete -c <name>`` per registered name.

    fish renders ``value\\tdescription`` pairs from ``-a`` output natively,
    so descriptions show without extra work. The glue strips the program
    name token and appends the 0-based index (fish's empty current token
    expands to zero arguments — the engine treats an index equal to the
    word count as "empty fragment").
    """
    blocks: list[str] = [
        f"# vesma fish completion — custom engine backed by `{prog_names[0]} __complete`.",
        f"# Installed by `{prog_names[0]} completion fish`; rewritten on every run.",
        "",
        "function __vesma_complete",
        "    set -l toks (commandline -opc)",
        "    "
        f"{prog_names[0]} __complete $toks[2..-1] (commandline -ct) "
        "(math (count $toks) - 1) 2>/dev/null",
        "end",
    ]
    for prog in prog_names:
        blocks.append(f"complete -c {prog} -f -a '(__vesma_complete)'")
    return "\n".join(blocks) + "\n"


def _completion_script(shell: str) -> str:
    """Generate the completion script for the given shell."""
    names = _prog_names()
    if shell == "bash":
        return _bash_script(names)
    if shell == "zsh":
        return _zsh_script(names)
    if shell == "fish":
        return _fish_script(names)
    raise ValueError(f"Unsupported shell: {shell}")


# ── Installer ─────────────────────────────────────────────────────────────────


def _is_installed(shell: str, rc: Path) -> bool:
    """Whether the rc file contains the EXACT canonical source line.

    Only a line equal (after stripping surrounding whitespace) to
    :func:`_canonical_source_line` counts. Commented lines, stale legacy
    forms (``vesmaro.bash``/``mnemos.bash`` sources, if-blocks, eval lines)
    never count — this is the fix for the historical false positive where a
    pre-rebrand ``source ~/.mnemos/completion/vesmaro.bash`` line made the
    installer report "already installed" while Tab completion was dead for
    ``vesma``.

    For fish, installation is the presence of the auto-sourced completions
    file for the primary program name.
    """
    if shell == "fish":
        return rc.exists()
    if not rc.exists():
        return False
    canonical = _canonical_source_line(shell)
    try:
        content = rc.read_text(encoding="utf-8")
    except OSError:
        return False
    return any(line.strip() == canonical for line in content.splitlines())


def _remove_old_completion_entries(rc: Path, shell: str) -> None:
    """Migrate away every legacy completion entry from the rc file.

    Removed (one line per match, no reflowing of the rest):

    * any line mentioning the completion directory that is NOT the exact
      canonical source line for this shell — pre-rebrand
      ``source ~/.mnemos/completion/vesmaro.bash`` lines,
      ``if [ -f ~/.mnemos/completion/mnemos.bash ]; then source …; fi``
      blocks, ``[ -f … ] && source …`` one-liners, wrong-shell/wrong-name
      references, and stale marker comments;
    * old ``eval "$(… --show-completion …)"`` lines (vesma/mnemos spelling);
    * old ``# Added by`` marker comments.

    Duplicate copies of the canonical line itself collapse to the first
    occurrence (exactly ONE canonical line stays).
    """
    if not rc.exists():
        return
    try:
        content = rc.read_text(encoding="utf-8")
    except OSError:
        return
    canonical = _canonical_source_line(shell)
    show_completion_re = re.compile(r"--show-completion", re.IGNORECASE)
    added_by_re = re.compile(r"#\s*Added by `vesma completion`")
    kept: list[str] = []
    canonical_seen = False
    for line in content.splitlines(keepends=True):
        stripped = line.strip()
        if stripped == canonical:
            if canonical_seen:
                continue  # dedupe: exactly one canonical line
            canonical_seen = True
            kept.append(line)
            continue
        if "mnemos/completion/" in line:
            continue  # any completion-dir mention that is not the canonical line
        if show_completion_re.search(line) or added_by_re.search(line):
            continue  # pre-custom-engine eval format and its markers
        kept.append(line)
    new_content = "".join(kept)
    if new_content != content:
        with contextlib.suppress(OSError):
            rc.write_text(new_content, encoding="utf-8")


def _write_script(path: Path, content: str) -> bool:
    """Write a completion script file; returns False (and reports) on error."""
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    except OSError as exc:
        console.print(f"[red]✗ Failed to write {path}: {exc}[/red]")
        return False
    return True


def _install(shell: str) -> bool:
    """Install completion for the given shell.

    Always rewrites the script file(s) so they stay in sync with the
    installed vesma version; migrates legacy rc entries; ensures exactly
    one canonical guarded source line in the rc file (bash/zsh) or one
    auto-sourced completions file per registered program name (fish).

    Returns True if installed (or already installed), False on write error.
    """
    script_file = _completion_file_path(shell)

    try:
        script = _completion_script(shell)
    except ValueError:
        console.print(f"[red]Unsupported shell: {shell!r}.[/red]")
        return False
    if not _write_script(script_file, script):
        return False

    if shell == "fish":
        # fish: write the auto-sourced completions file per registered name
        # (fish sources ~/.config/fish/completions/<name>.fish when the user
        # completes <name> — aliases need their own file, one script each).
        for prog in _prog_names():
            target = _fish_completions_file(prog)
            if not _write_script(target, script):
                return False
        console.print(f"[green]✓[/green] Installed {shell} completion → {script_file}")
        console.print(
            f"  [dim]Auto-sourced copies: "
            f"{', '.join(str(_fish_completions_file(p)) for p in _prog_names())}[/dim]"
        )
        return True

    # bash/zsh: migrate ALL legacy forms, then ensure the canonical line.
    rc = _rc_path(shell)
    _remove_old_completion_entries(rc, shell)

    if _is_installed(shell, rc):
        console.print(f"[green]✓[/green] Completion for {shell} installed at {script_file}")
        console.print(f"  [dim]Source line already present in {rc}[/dim]")
        return True

    try:
        rc.parent.mkdir(parents=True, exist_ok=True)
        with rc.open("a", encoding="utf-8") as fh:
            # Single-quoted marker: the migration regex targets the OLD
            # double-quoted `# Added by \`vesma completion\`` comments, this
            # fresh marker must survive re-runs.
            fh.write(f"\n# Added by 'vesma completion' ({shell}) — custom __complete engine\n")
            fh.write(f"{_canonical_source_line(shell)}\n")
    except OSError as exc:
        console.print(f"[red]✗ Failed to write {rc}: {exc}[/red]")
        return False
    console.print(f"[green]✓[/green] Installed {shell} completion → {script_file}")
    console.print(f"  [dim]Source line added to {rc}[/dim]")
    console.print(f"  [dim]Restart your shell or run: source {rc}[/dim]")
    return True


# ── Manual instructions ────────────────────────────────────────────────────────


def _print_instructions() -> None:
    """Print manual install instructions for all supported shells."""
    console.print("[bold]Manual completion installation[/bold]\n")
    console.print(
        "Candidates carry descriptions: zsh and fish SHOW them; bash's readline "
        "cannot render descriptions, so bash completes values only.\n"
    )
    for shell in _SUPPORTED_SHELLS:
        script_file = _completion_file_path(shell)
        rc = _rc_path(shell)
        if shell == "fish":
            console.print(f"[bold cyan]{shell}[/bold cyan]  →  {rc} (auto-sourced)")
            console.print(f"    Copy also stored at {script_file}")
        else:
            console.print(f"[bold cyan]{shell}[/bold cyan]  →  {script_file}")
            console.print(f"    {rc.name}: {_canonical_source_line(shell)}")
            if shell == "zsh":
                console.print("    Put the source line AFTER compinit in your .zshrc.")
        console.print()


# ── Command ───────────────────────────────────────────────────────────────────


@completion_app.callback(invoke_without_command=True)
def completion(
    shell: Annotated[
        str | None,
        typer.Argument(
            help="Shell to install completion for (bash/zsh/fish). "
            "If omitted, auto-detects from $SHELL.",
        ),
    ] = None,
    show_instructions: Annotated[
        bool,
        typer.Option(
            "--show-instructions",
            help="Print manual install instructions without modifying any files.",
        ),
    ] = False,
) -> None:
    """Install shell completion for vesma.

    With no arguments: auto-detects the current shell from ``$SHELL`` and
    auto-installs the custom completion script (backed by ``vesma
    __complete`` — commands, subcommands, options and option values, WITH
    descriptions where the shell can show them) plus a single canonical
    ``source`` line in the rc file. Idempotent — re-running rewrites the
    scripts and keeps exactly one canonical source line, migrating away all
    legacy forms (old eval lines, pre-rebrand vesmaro/mnemos script names,
    if-blocks and one-liner sources).

    Pass an explicit shell (bash/zsh/fish) to override auto-detection.

    Use ``--show-instructions`` to print the manual steps for all supported
    shells without modifying any files.
    """
    if show_instructions:
        _print_instructions()
        raise typer.Exit(0)

    target = shell or _detect_shell()
    if target is None:
        console.print(
            "[red]Could not auto-detect your shell from $SHELL.[/red]\n"
            "Pass an explicit shell: [bold]vesma completion bash|zsh|fish[/bold]\n"
            "Or see manual steps: [bold]vesma completion --show-instructions[/bold]"
        )
        raise typer.Exit(1)

    if target not in _SUPPORTED_SHELLS:
        console.print(
            f"[red]Unsupported shell: {target!r}.[/red]\nSupported: {', '.join(_SUPPORTED_SHELLS)}"
        )
        raise typer.Exit(1)

    ok = _install(target)
    if not ok:
        raise typer.Exit(1)


def _detect_shell() -> str | None:
    """Detect the current shell from ``$SHELL``.

    Returns the bare shell name (``bash``/``zsh``/``fish``) or ``None`` if
    unknown/unsupported.
    """
    raw = os.environ.get("SHELL", "")
    if not raw:
        return None
    name = raw.split("/")[-1].lower()
    if name in _SUPPORTED_SHELLS:
        return name
    return None
